kreyu_auth_prototype_login:
  path: /login
  controller: Kreyu\Bundle\AuthPrototypeBundle\Controller\SecurityController::login
  methods: GET|POST

kreyu_auth_prototype_logout:
  path: /logout
  controller: Kreyu\Bundle\AuthPrototypeBundle\Controller\SecurityController::logout
  methods: GET|POST
